name: CI

on:
  push:
    branches: [main, ci-*]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
          submodules: recursive
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npm install
      - run: npm run lint:format
      - run: npm run lint
  test:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16', '18', '20']
    name: Testing on node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
          submodules: recursive
      - run: sudo apt-get update
      - run: sudo apt-get install -y libxml2-utils
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      # Setup Python for ipykernel & jupyter-server
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: python -m pip install jupyter-server ipykernel
      - run: npm install
      - run: npm run test
